[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/var/lib/odoo/.local/share/Odoo/addons/16.0,/mnt/extra-addons
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo
workers = 2
max_cron_threads = 1
ir_attachment_location = db
admin_passwd = $pbkdf2-sha512$600000$6D0H4DwHYIzR2hsjRMh5jw$ns8QLc.RQSOqgsjZAm1GteD6nZZfLAg9ogLRbaH1EfzB1AM0IF7RoUTBrB9gnQY7NMqNAEfe9dm54Hie2tDw9A

